services:
    Projects\core\app\Resources\DemosPlanCoreBundle\Logic\Permissions:
        autowire: true

    DemosEurope\DemosplanAddon\Contracts\PermissionsInterface: '@Projects\core\app\Resources\DemosPlanCoreBundle\Logic\Permissions'
