parameters:
  allowed_mimetypes:
    - application/pdf
    - application/x-pdf
# *download ist FF pdf https://bugzilla.mozilla.org/show_bug.cgi?id=373621
    - application/download
    - application/x-download
    - application/x-compressed
    - application/zip
    - application/octet-stream
    - application/msword
    - image/bmp
    - image/gif
    - image/jpeg
    - image/pjpeg
    - image/png
    - image/tiff
    - image/webp
    - image/x-png
    - text/plain
    - text/csv
# text/html f√ºr den Paragraph HTML-Importer
    - text/html
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/msword
# txt Datei mit 0 bytes werden als inode/x-empty erkannt
    - inode/x-empty
    - video/mp4
    - video/webm
# additional mimetype for excel upload
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    - application/vnd.ms-excel
    - application/vnd.oasis.opendocument.spreadsheet
